name: Publish Docker Image

on:
  release:
    types: [ published ]
  schedule:
    - cron: '0 3 * * 3'
  workflow_dispatch:

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      max-parallel: 1
      matrix:
        variant: [ "", slim, rc, rc-slim ]
        os: [ "", trixie, bookworm, alpine ]
        exclude:
          - os: alpine
            variant: slim
          - os: alpine
            variant: rc-slim
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine root image name
        run: |
          echo "BASE_NAME=$(grep -m1 '^FROM' Dockerfile | cut -d' ' -f2 | cut -d':' -f1)" >> $GITHUB_ENV

      - name: Determine root image tag
        run: |
          if [[ -n "${{ matrix.os }}" && -n "${{ matrix.variant }}" ]]; then
            echo "BASE_TAG=${{ matrix.os }}-${{ matrix.variant }}" >> $GITHUB_ENV
          elif [[ -z "${{ matrix.os }}" && -z "${{ matrix.variant }}" ]]; then
            echo "BASE_TAG=latest" >> $GITHUB_ENV
          else
            echo "BASE_TAG=${{ matrix.os }}${{ matrix.variant }}" >> $GITHUB_ENV
          fi
      - name: Set correct base image
        run: |
          sed -i "s/.*FROM.*/FROM ${{ env.BASE_NAME }}:${{ env.BASE_TAG }}/" Dockerfile

      - name: Define correct arhitectures
        run: |
          if [[ "${{ matrix.os }}" == "trixie" || -z "${{ matrix.os }}" ]]; then
            echo "ARCH=linux/amd64,linux/arm64/v8,linux/riscv64" >> $GITHUB_ENV
          else
            echo "ARCH=linux/amd64,linux/arm64/v8" >> $GITHUB_ENV
          fi

      - name: Show Dockerfile
        run: cat Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: Dockerfile
          context: .
          platforms: "${{ env.ARCH }}"
          tags: dantes2104/linstor-client-docker:${{ env.BASE_TAG }},ghcr.io/edmondantes/linstor-client-docker:${{ env.BASE_TAG }}